### ISSUE TITLE
Missing functions - triangle and textAlign

### ISSUE THREAD

**Issue by igordsm** [Acepie/p5js_gleam#4]
Hello, I'm creating sketch using this wrapper and there's some p5.js functions I'm missing:

- triangle
- textAlign

I've read the code and the fix seems simple. The only problem would be that textAlign seems to allow optional arguments and that might be a problem. Other than that, I could send a PR for this if think that's good. 

BTW, here's a video of my sketch. You can see that the text is not aligned to the center of the vertex nodes and it looks really ugly.

https://github.com/user-attachments/assets/bf41c835-332e-4c8f-a65b-b409c72997af

**Comment by Acepie** [comment]
Hi, generally since p5js pruposefully allows a lot of different versions of the same function, I've been adding the version that is most explicit/requires the most arguments. This gives the flexibility that people want while keeping the type checking reasonable

**Comment by Acepie** [comment]
I've added triangle and textAlign as part of v3.0.0

https://hexdocs.pm/p5js_gleam/p5js_gleam/bindings.html#triangle
https://hexdocs.pm/p5js_gleam/p5js_gleam/bindings.html#text_align

as well as helper constants for use with text_align
